import Head from "next/head";
import Broadcast from "../components/Broadcast";
import Faq from "../components/Faq";
import Landing from "../components/Landing";
import Nav from "../components/Nav";
import TheGang from "../components/TheGang";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Yin Yang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Landing />
      <TheGang />
      <Broadcast />
      <Faq />
    </div>
  );
}
